#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

#### KUBERNETES DOCKER-REGISTRY SECRET CREATION START ####
- name: Create Docker Registry secret
  command: kubectl create secret docker-registry "{{ kube_docker_registry_secret_name }}" --docker-server="{{ kube_docker_registry_server }}" --docker-username="{{ kube_docker_registry_username }}" --docker-password="{{ kube_docker_registry_pwd }}" --docker-email="{{ kube_docker_registry_email }}"
  ignore_errors: true
  when: "{{ kube_docker_registry_secret_name }}"
  tags:
    - deploy_apps_in_kube
#### KUBERNETES DOCKER-REGISTRY SECRET CREATION END ####

#### PROVISION APP TO KUBERNETES START ####
# TODO: This needs to be updated to support more than just Kubernetes application files.
#       Ultimately more than just this playbook will use the file input type and we need
#       to support those also. Copying the entire prepare folder is a stopgap until the
#       Python logic changes can be made to support placing the Kubernetes app files in
#       their own location.
- name: Copy files to Kubernetes master
  copy:
    src: "/var/lib/chaperone/prepare"
    dest: "/tmp"
  tags:
    - deploy_apps_in_kube

- name: Get the list of files
  command: find /tmp/prepare -type f -printf "%f\n"
  register: kube_app_files
  tags:
    - deploy_apps_in_kube

- name: Echo the file list
  debug:
    msg: "{{ kube_app_files.stdout_lines }}"
  tags:
    - deploy_apps_in_kube

- name: Provision the apps
  command: kubectl create -f "{{ item }}"
  args:
    chdir: "/tmp/prepare"
  with_items:
    - "{{ kube_app_files.stdout_lines }}"
  tags:
    - deploy_apps_in_kube
#### PROVISION APP TO KUBERNETES END ####

#### DESTROY APPS IN KUBERNETES START ####
- name: Destroy the apps
  command: kubectl delete -f "{{ item }}"
  args:
    chdir: "/root/prepare"
  with_items:
    - "{{ kube_app_files.stdout_lines }}"
  tags:
    - destroy_apps_in_kube
#### DESTROY APPS IN KUBERNETES END ####
