---
- name: test for kubernetes installed
  command: rpm -q kubernetes
  register: kubernetes_installed
  ignore_errors: yes
  changed_when: False
  tags:
    - packages

- name: test for flannel installed
  command: rpm -q flannel
  register: flannel_installed
  ignore_errors: yes
  changed_when: False
  tags:
    - packages

- name: install kubernetes
  yum:  name={{ kubernetes_package }} state=present
  when: kubernetes_installed.rc == 1
  tags:
    - packages

- name: install flannel
  yum:  name={{ flannel_package }} state=present
  when: flannel_installed.rc == 1
  tags:
    - packages

- name: allow cert creation
  file: group=kube owner=kube path=/var/run/kubernetes/ state=directory recurse=yes

- name: Set up configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ kube_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - apiserver
    - config
  notify:
    - restart kube-apiserver
    - restart kube-controller-manager
    - restart kube-scheduler

- name: Set up services
  template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload
    - restart etcd
    - restart flannel
  with_items:
    - flannel
    - etcd

- name: initial start services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - etcd
    - flannel
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
