apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-apache
  labels:
    name: myapp-apache
spec:
  replicas: 3
  selector:
    name: myapp-apache
  template:
    metadata:
      labels:
        name: myapp-apache
    spec:
      containers:
        - name: myapp-apache
          image: tutorials/myapp-apache
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping.php
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1