---
- name: daemon reload
  command: systemctl daemon-reload

- name: restart etcd
  service:
    name: etcd
    state: restarted
    enabled: yes

- name: restart flannel
  service:
    name: flannel
    state: restarted
    enabled: yes

- name: restart kube-apiserver
  service:
    name: kube-apiserver
    state: restarted
    enabled: yes

- name: restart kube-controller-manager
  service:
    name: kube-controller-manager
    state: restarted
    enabled: yes

- name: restart kube-scheduler
  service:
    name: kube-scheduler
    state: restarted
    enabled: yes
